name: lint-test
on:
  push:

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: ">=1.25.3"

      - uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          version: latest

      - name: Install dependencies
        run: go get .

      - name: Test with the Go CLI
        run: go test -v ./...

  build-push:
    needs: [lint-test]
    uses: lehigh-university-libraries/gha/.github/workflows/build-push-ghcr.yaml@main
    permissions:
      contents: read
      packages: write
    secrets: inherit
